version: '3'
services:
    db:
      image: postgres:alpine
      hostname: postgres
      environment:
        POSTGRES_DB: paypay
      # ports:
      #   - 5432:5432
    backend:
        build: ./backend
        environment:
          ENV: DEV
          POSTGRES_CONNECTION: postgresql://postgres@db:5432?sslmode=disable
        # ports:
        #   - 8000:8000
        links:
          - db
    frontend:
        build: ./frontend
        environment:
          ENV: DEV
          DEV_FRONTEND_PROXY: "http://backend:8000/"
        ports:
          - 3000:3000
        links:
          - backend